### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by htzh** [ocaml-omake/omake#115]
I am trying to compile the [MetaPRL](https://github.com/jyh/metaprl) project, which I believe is where OMake originated. It has trouble linking with camlp5 even though "-I" directory appears to be correctly passed. I get

```
*** omake: reading OMakefiles
*** omake: finished reading OMakefiles (0.84 sec)
- build util macro_main.cmi
+ ocamlc.opt -warn-error Aez-3-7-29-37-44-45-50 -w Aez-3-7-29-37-44-45-50 -thread -pp 'camlp5r -I /home/.../.opam/system/lib/camlp5 -nolib -loc _loc' -g -I . -I /usr/lib/ocaml/compiler-libs -I /home/.../.opam/system/lib/camlp5 -c macro_main.ml
File "macro_main.ml", line 1, characters 0-12:
Error: Unbound module Odyl_main
*** omake: 359/4119 targets are up to date
*** omake: failed (4.08 sec, 74/74 scans, 1/29 rules, 1/326 digests)
*** omake: targets were not rebuilt because of errors:
   util/macro_main.cmi
      depends on: util/macro_main.ml
   util/macro_main.cmo
      depends on: util/macro_main.ml
   util/macro_main.cmx
      depends on: util/macro_main.ml
   util/macro_main.o
      depends on: util/macro_main.ml
```

Unfortunately I don't know anything about OMake. Could someone take a look at the [OMakefile](https://github.com/jyh/metaprl/blob/master/util/OMakefile) and tell me if everything is alright?

**Comment by ANogin** [comment]
I am guessing the version of camlp5 you build did not install odyl_main.cmi / odyl_main.mli into /home/.../.opam/system/lib/camlp5 - you would need to either change tweak the install part of camlp5 build, or copy these two files our of the camlp5 build manually.

**Comment by ANogin** [comment]
P.S. In any case, this has nothing to do this OMake - I suggest closing this issue here.

**Comment by htzh** [comment]
You are right that odyl_main.* are not installed. I installed camlp5 through opam. I will see if I can find the files manually.

Thanks for the quick response. I wasn't sure if anyone would respond to issues at MetaPRL. I will close this thread and follow up over at MetaPRL.
