### ISSUE TITLE
Undocumented special dependency specifier `:squash:`

### ISSUE THREAD

**Issue by LdBeth** [ocaml-omake/omake#136]
I find it has been used in MetaPRL's OMakefiles.

https://github.com/owo-lang/metaprl/blob/a5fe92672d0aad30ee9f7bb9daffe8e3d456a68a/OMakefile_theories#L87

It seems that `:squash:` is just an alias to `:exists`, or at least similar to it, by https://github.com/ocaml-omake/omake/blob/05caf981ad343434e3125598224ff73996087bfb/src/ir/omake_cache.ml#L871

However change it to `:exists` gives this error:
```
*** omake error:
   File OMakefile_theories: line 87, characters 1-53
   Do not know how to build "<scanner theories/itt/reflection/base/scan-ocaml-reflect_itt_hoas_base_theory.ml>" required for "theories/itt/reflection/base/reflect_itt_hoas_base_theory.cmo"
```

**Comment by ANogin** [comment]
`A :exists: B` dependency: A can be built without B, but if A appears/disappears afterwards, B needs to be rebuilt.
`A :squash: B` dependency: A cannot be built without B (build B first, and only then build A), but if B changes afterwards, A does not need to be rebuilt.

Yes, definitely should have been documented.

**Comment by cspiel** [comment]
@ANogin, I think you got the order wrong with `:exist`:
... if B appears/disappears afterwards, A needs to be rebuilt.

In particular, if the contents of B changes, A is not considered
out-of-date.

As we are talking about undocumented specials, IFAIKS,
the manual neither covers `:normal:`.

**Comment by cspiel** [comment]
Improved documentation wrt special dependencies in #137
