### ISSUE TITLE
Compatibility with OCaml 5.0

### ISSUE THREAD

**Issue by jhwoodyatt** [ocaml-omake/omake#152]
OMake 0.10.5 is not compatible with OCaml 5.0. It currently fails to build because it still requires the `Pervasives` module in the standard library, which was removed in OCaml 5.0.

**Comment by gerdstolpmann** [comment]
See #153 for the necessary changes. @jhwoodyatt can you test?

**Comment by jhwoodyatt** [comment]
> See #153 for the necessary changes. @jhwoodyatt can you test?

I'll check it out sometime this weekend. I'll be checking to see if it also compiles with the effect syntax enabled, which I know  has been a source of build issues on the multicore branch.

**Comment by jhwoodyatt** [comment]
> > See #153 for the necessary changes. @jhwoodyatt can you test?
> 
> I'll check it out sometime this weekend. I'll be checking to see if it also compiles with the effect syntax enabled, which I know has been a source of build issues on the multicore branch.

I'm satisfied that #153 corrects the error. It would be nice to see a new release containing this change land in OPAM.

**Comment by chenrui333** [comment]
Any timeline to make an ocaml 5 compatible release? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/118465

**Comment by gerdstolpmann** [comment]
I promise I'll look into this the next days...

**Comment by chenrui333** [comment]
Thanks @gerdstolpmann!

**Comment by jhwoodyatt** [comment]
Thanks!
