### ISSUE TITLE
Another way of avoiding bootstrapping

### ISSUE THREAD

**Issue by bobzhang** [ocaml-omake/omake#50]
In BuckleScript, we developed a tool called bspack, will pack all files into a single file, this is extremely helpful for easy distribution, there are no dependencies, easy to make it work on windows.
Note `bspack` will search all modules based on `-I` and  an entry point, it will sort out those modules automatically, we did it for several non-trivial projects, even for the whole OCaml compiler, it works pretty well, so I am thinking of using `bspack` to bundle all omake files into a single module for easy consumption, what do you think?

**Comment by gerdstolpmann** [comment]
Well, thanks for reporting this. If the bootstrapping problem would have had solved yet, I'd certainly take this into account. However, we are now at a point where the bootstraps work fairly well, both for development purposes and for release purposes.

Generally, we don't want to avoid bootstrapping. Building the build tool with the build tool is a very good test. So, I'd consider such a tool at most for creating the bootstrap version of omake (i.e. only for the first phase of the bootstrap), as a simple-to-use generic build utility.

Also, we have a number of complicattions, e.g. the automatic adaptions to the operating system and the alignment of the boot configuration with the later runtime configuration (regarding compiler switches etc.). Not sure how simple it would be to do this with your suggestion. My guess is that you get headache anyway, and you are only free to select which kind.
