### ISSUE TITLE
omake creates files with the executable bit set on Windows

### ISSUE THREAD

**Issue by nojb** [ocaml-omake/omake#52]
Hi, we are using `omake` under Cygwin and if you create an `OMakefile` with the rule

    .PHONY: foo
    foo:
        echo hello > foo.txt

then the file `foo.txt` is created with executable permissions set.  Is this a known issue ? Is there any workaround ? 

This is an `omake` issue, as the same example with plain `make` does not set the executable bit of `foo.txt`.

**Comment by gerdstolpmann** [comment]
This could be an omake issue, not sure.

**Comment by nojb** [comment]
Actually we studied this a little more and it turns out that it is a Windows/Cygwin issue: we are using the native Win32 `omake` under Cygwin.  Cygwin seems to set the executable bit of the root directory.  Moreover this flag is inherited by any new file/directory created under it.  Somehow native Cygwin apps compensate for it and do not create files with executable permission, but all native Win32 apps running under Cygwin seem to do so.

Sorry for the noise, closing this as it is *not* an `omake` issue.
