### ISSUE TITLE
Possible bug in variable expansion of scanner rules?

### ISSUE THREAD

**Issue by sbriais** [ocaml-omake/omake#53]
Please find a very small OMake project. We are wondering why it does not work.

The idea is the following:
- we have an external tool that computes the dependencies needed for some files (typically a ppx), here we generate a dummy script depend.sh
- the scanner rule is written in a generic way but it depends on a variable (here called COMPUTEDEPS) which is set when needed

For the attached project, we have defined a scanner rule for C files (called scan-gccplouf-%.c) which depends on the C file and the value of the variable COMPUTEDEPS.

We generate a dummy file main.c.

We generate a dummy script shell depend.sh that returns the dependencies needed to build the %.o file.

We define a generic rule for building %.o file that depends on the %.c file and the scanner scan-gccplouf-%.c

We have set the variable COMPUTEDEPS after the definition of the .SCANNER which is equal to $(file depend.sh).

We have two scenario:
1. If we run omake (on linux), we get an error, because it does not build depend.sh before running the scanner. Of course, if we run "omake depend.sh" before, it works.
2. If we move the definition of COMPUTEDEPS before the .SCANNER, this works. But of course, in our situation, we cannot do this. 

Note that I commented two "echo" commands. This allows to inspect the value of COMPUTEDEPS when running the rules. You'll see that in both scenario, the content of log file is correct (contains depend.sh).

[scanner.zip](https://github.com/ocaml-omake/omake/files/541146/scanner.zip)

Any ideas or comments?

In addition, in our use case, we have the feeling that the value of the variable inside the scanner rules is bad (the path of the file is not good), does it ring a bell?

**Comment by gerdstolpmann** [comment]
Frankly, I don't get what you really want to do. Your OMakefile doesn't work because variables are eager in omake. Not sure whether this helps you but lazy evaluation is also available:

```
COMPUTEDEPS = $`(file ./depend.sh)
```

Note the backtick.

**Comment by sbriais** [comment]
The lazy evaluation does not work.

I'll try to give an overview of what we try to achieve. I hope you will understand better what we want to do.

We have generic scanner rules for our ml/mli/mf/mfi (mf/mfi are LexiFi ml/mli files). It looks like:

.SCANNER: scan-mlfi-%.mfi: %.mfi $(MLFIDEP_DEPS)
  $(MLFiScanner $<)

Some of our mfi files are used to generate mf files, thanks to our gen_js_api preprocessor. 
In order to get the dependencies for the cmi, we need to build first our preprocessor (it is passed as an argument to ocamldep with the -ppx flag).
So for these files, we extend MLFIDEP_DEPS to include gen_js_api executable, ie we have a section where we do:
MLFIDEP_DEPS += $(file $(DIR_ojs)/gen_js_api$(EXE))

Unfortunately, omake fails building our project, because it does not understand that it needs gen_js_api executable in order to be able to run the scanner on these files.

I tried to minimize the example so that you can see the idea. In this example, I say that I have a generic scanner rule to analyse C files. For some of the C files, but not all, I want to use the script depend.sh to generate the dependencies. Here, it is a bit artificial since there is only one C file...

**Comment by gerdstolpmann** [comment]
hmmm, it could be that the scoping is in the way. When you do
```
MLFIDEP_DEPS += $(file $(DIR_ojs)/gen_js_api$(EXE))
```
in a section this doesn't change the global value of this variable. Not even when you export it - this doesn't change rules that have already been set. What you could try is to repeat the scanner rule (w/o body) in the section after extending MLFIDEP_DEPS, something like

```
section
    MLFIDEP_DEPS += $(file $(DIR_ojs)/gen_js_api$(EXE))
    .SCANNER: scan-mlfi-%.mfi: %.mfi $(MLFIDEP_DEPS)
```

The dependency tree as such is one of the few things that are truly global, so changing it anywhere will have a global effect.

**Comment by sbriais** [comment]
Actually, it was not in a section but the body of a function. But ok, thanks, this seems to work.

**Comment by alainfrisch** [comment]
My understanding was that implicit rules would be copied over subdirectories (included with .SUBDIRS), and be evaluated at the end of the corresponding OMakefile.  But Sebastien's original example does not seem to work even if everything starting from the line `COMPUTEDEPS = $(file ./depend.sh)` is moved to a subdirectory.

**Comment by gerdstolpmann** [comment]
When I remember correctly, variables in the dependency line are evaluated immediately when you define a rule (other than the variables in the rule body which are first evaluated when the rule is executed and which pick up the scope at the end of the OMakefile). Also, at the end of the OMakefile rules with patterns (`%` placeholders) are applied to the files/targets in that directory.

**Comment by gerdstolpmann** [comment]
This seems to be more a wrong interpretation of the omake DSL than a real issue.
