### ISSUE TITLE
rm -rf does not work on Windows

### ISSUE THREAD

**Issue by sbriais** [ocaml-omake/omake#60]
There is a regression in the implementation of rm -rf on Windows.

unlink a directory on windows raises EACCESS not EISDIR.

**Comment by gerdstolpmann** [comment]
I made a PR for this: https://github.com/ocaml-omake/omake/pull/61
Can you please check whether this is working?

**Comment by sbriais** [comment]
Actually, this seems to be the POSIX behaviour, not windows specific.
see http://pubs.opengroup.org/onlinepubs/009695399/functions/unlink.html
I'll try your PR tomorrow.

**Comment by gerdstolpmann** [comment]
That page describes EPERM as the code when you unlink a directory. Added this to the PR.

**Comment by sbriais** [comment]
Our build at LexiFi now works: thank you!

PS: there is a minor issue on windows, sometimes omake fails to delete its temporary files (/tmp/omake*.shell) Not deterministic, not easy to reproduce, but I mention that in case you have an idea about that problem. Our current workaround is to delete manually the file and launch the build again.

**Comment by gerdstolpmann** [comment]
Fix merged.
