### ISSUE TITLE
How to uninstall omake correctly?

### ISSUE THREAD

**Issue by rgrinberg** [ocaml-omake/omake#67]
Currently, doing `$ opam remove omake` leaves some lingering files around.

https://github.com/ocaml/opam-repository/pull/7857#issuecomment-264194365

Is it safe to just rm -rf that directory as a stop gap measure.

**Comment by gerdstolpmann** [comment]
Yes, i think it is safe to remove the lib/omake directory entirely. There is no reason why other packages would install files there.

**Comment by gerdstolpmann** [comment]
Closing because I think we have a PR https://github.com/ocaml-omake/omake/pull/69
