### ISSUE TITLE
Change in string-escaping behavior between 0.9.* and 0.10.1

### ISSUE THREAD

**Issue by smondet** [ocaml-omake/omake#72]
Don't know if this is a bug, or just a backwards-incompatible change.

Our builds fail with 0.10.1 because we use OMake to generate some code with
`echo`
(e.g. this [one](https://travis-ci.org/hammerlab/biokepi/jobs/180576476) at [`OMakeroot:53`](https://github.com/hammerlab/ketrew/blob/master/OMakeroot#L53)).

The behavior of the quotes/strings escaping has changed:

```
 $ omake --version
OMake 0.9.8.6 (release candidate 1):
	build [Mon Dec 5 15:25:51 2016]
	on sebxps

Default library directory : /home/smondet/.opam/4.03.0/lib/omake

 $ osh
% GIT_COMMIT = 'Some "$(shell git rev-parse HEAD)"'
- : <data "Some \"c099314e9a316b567013ca791c51367ba6a7609a\""> : String
% echo "let git_commit = $(GIT_COMMIT)"
let git_commit = Some "c099314e9a316b567013ca791c51367ba6a7609a"
% 
```

```
 $ omake --version
OMake 0.10.1 (development snapshot):\n\tbuild [Mon Dec 5 15:19:51 2016]\n\ton sebxps

Default library directory : /home/smondet/.opam/4.03.0/lib/omake

 $ osh
% GIT_COMMIT = 'Some "$(shell git rev-parse HEAD)"'
- : <string '
       <data "Some \"c099314e9a316b567013ca791c51367ba6a7609a\""> : String'>
       : String
% echo "let git_commit = $(GIT_COMMIT)"
let git_commit = 'Some "c099314e9a316b567013ca791c51367ba6a7609a"'
% 
```

**Comment by gerdstolpmann** [comment]
This was actually a bug in 0.9.8.6. omake should not remove quotes (unless you use the special quotes $"..." or $'...'). See https://github.com/ocaml-omake/omake/issues/29.

In this case you can simply remove the single quotes. Should work in both versions.
