### ISSUE TITLE
OCamlPackage does not work correctly when the pack does not have an mli file

### ISSUE THREAD

**Issue by gerdstolpmann** [ocaml-omake/omake#73]
Assume there is a pack p containing some modules
```
OCamlPackage(p, m1 m2 m3)
```
Also assume that there is no file `p.mli`. In this case, the cmi file is generated by `OCamlPackage`. If we look only at the dependencies emitted by `OCamlPackage` everything is right. The deps look like:
```
p.cmo p.cmi: m1.cmo m2.cmo m3.cmo
p.cmx p.o p.cmi: m1.cmx m1.o m2.cmx m2.o m3.cmx m3.o
```
The problem is now that the dependency scanner for the users of the pack in the same project do not see that the module P exists (at least until the file p.cmi is created). Hence, no dependency on P is ever generated. This does not work because there is no file indicating the existence of P. The result are incorrectly sequenced builds that break from time to time.

Note that the `OCamlPackage` function would not allow it to generate the mli file to work around the problem.

As we use files for determining the toplevel modules there is no chance to fix this unless we interpret another file suffix. E.g. the presence of file `p.nomli` could be seen as indicator that `P` exists, and the dependencies on `P ` are then emitted.

**Comment by camlspotter** [comment]
I use my modified version of `OCamlPackage` for my packages, but the diff is only to produce `*.cmt` files, so the interface inconsistency issues of my packages should related with this.

**Comment by gerdstolpmann** [comment]
Looks like that there is a different reason for the build failures I observed. If we build a mixed build/native project, we run two commands for packing P, one generating p.cmi and p.cmo, and another one generating p.cmi, p.cmx and p.o. The problem is now that there is nothing that prevents the following sequencing:

 - we pack byte code: p.cmi, p.cmo
 - we do the following in parallel:
   * we build a byte code descendent of P
   * we pack native code: p.cmi, p.cmx, p.o

The last two actions must not run in parallel, because p.cmi is overwritten again while the descendent needs p.cmi.

There seems to be nothing in the build driver that prevents such situations (i.e. ensure that a command building a file and a command using a file cannot run in parallel). Because of this, the build rules for the modules are formulated so that we cannot run into this problem - there is a combined rule:

```
%.cmx %.cmi %$(EXT_OBJ) %.cmo: %.ml :scanner: scan-ocaml-%.ml
    $(OCamlC) -c $<
    $(OCamlOpt) -c $<
```

I guess we need to change OCamlPackage accordingly, i.e. pack both byte code and native code together in one step, so far both targets are enabled.

**Comment by gerdstolpmann** [comment]
Created PR: https://github.com/ocaml-omake/omake/pull/80

**Comment by alainfrisch** [comment]
Ah, I realize that the trick I was referring to is in our local build rules, not in OMake ones.  Our rule is:

````
%.cmx: %.ml
    section rule
        if $(not $(NATIVE_ENABLED))
            err. =
                extends $(UnbuildableException)
                message = $(string $"You are trying to build MLFi native code file: "%.cmx$"
However, the NATIVE_ENABLED flag is not set.
Include the following definition in your OMakefile
if you really want to build this file.
       NATIVE_ENABLED = true")
                target = $(file %.cmx)
            raise $(err)
        elseif $(target-exists %.mli)
            %.cmx %$(EXT_OBJ): %.ml %.cmi $(MLFIOPT_DEPS) :scanner: scan-mlfi-%.ml
                $(MLFiOpt $<) -c $<
        elseif $(BYTE_ENABLED)
            %.cmx %$(EXT_OBJ): %.ml %.cmi $(MLFIOPT_DEPS) :scanner: scan-mlfi-%.ml
                $(MLFiOpt $<) -c -intf-suffix .cmi $<
        else
            %.cmx %.cmi %$(EXT_OBJ): %.ml $(MLFIOPT_DEPS) :scanner: scan-mlfi-%.ml
                $(MLFiOpt $<) -c $<
````

(and a similar one for `%$(EXT_OBJ): %.ml`)

The trick is to consider that ocamlc will build the .cmi (inferred signature) and that ocamlopt should consider this .cmi as a dependency, as if it had been produced from an explicit .mli.  This is achieved by passing `-intf-suffix .cmi` to ocamlopt.  The makes ocamlopt believe that the unit as an explicit interface file.

**Comment by gerdstolpmann** [comment]
This is fixed as good as we can do it at the moment. There is now https://github.com/ocaml-omake/omake/issues/82 for tracking any further possibilities for improvement.
