### ISSUE TITLE
RPEFIX var confusion

### ISSUE THREAD

**Issue by rgrinberg** [ocaml-omake/omake#74]
Looks  like there's some unwanted behavior here:

https://github.com/ocaml/opam-repository/pull/8058

After passing the correct -prefix to configure, I don't expect this to be overrideable in the command line. Perhaps an error in this situation is warranted?

**Comment by gerdstolpmann** [comment]
Well, this is actually the "classic behavior", i.e. any traditional Makefile-based build behaves like that. Not sure what to do with this. There could be other environment variables, too.

**Comment by gerdstolpmann** [comment]
Just found where it is set: see line 84 of mk/default. There is a second mechanism, using `$(INSTALL_ROOT)` for installing into a staging directory. Maybe just interpret this variable, and remove all the other stuff? You can also override BINDIR and LIBDIR.

**Comment by gerdstolpmann** [comment]
Created a PR: https://github.com/ocaml-omake/omake/pull/81

**Comment by gerdstolpmann** [comment]
Fix merged
