### ISSUE TITLE
OMake Install Failure - ?

### ISSUE THREAD

**Issue by krpcannon** [ocaml-omake/omake#75]
All:

Need to install OMake for use with Teyjus Lambda Prolog system. My installation is seemingly failing and would like to know where to address it and why. I'm a student of CS and maybe this will appear trivial to many.

I used 'opam install omake' and it appeared successful. After running an omake command, I get the response "bash: omake: command not found" 

Yet, after retrying opam install, it says already installed.

**Comment by gerdstolpmann** [comment]
I guess you should do
```
eval $(opam config env)
```
which, among other things, extends the PATH variable as needed

**Comment by krpcannon** [comment]
Thanks!! Link to document on that command?
