### ISSUE TITLE
omake doesn't compile with OCaml 4.06

### ISSUE THREAD

**Issue by jpdeplaix** [ocaml-omake/omake#95]
The upcoming OCaml release (4.06) has now safe-string enabled by default. However omake isn't compatible with safe-string yet.

I don't have time to make a PR but I'd be happy to give any kind of help in fixing this.

**Comment by gerdstolpmann** [comment]
Created https://github.com/ocaml-omake/omake/pull/96 in the meantime.

Is there an OCaml version around that already sets safe-string by default? It would be a good test case.

**Comment by jpdeplaix** [comment]
Awesome ! Thanks !!
You can try with any of the OPAM switches suffixed with ```+safe-string``` such as ```4.04.2+safe-string``` or ```4.05.0+safe-string```.
I just tried with both ```4.02.3``` and ```4.04.2+safe-string``` and it seems to compile perfectly.
